apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dreamfactory.fullname" . }}-secret
type: Opaque
data:
  app-key: {{ randAlphaNum 32 | b64enc | quote }}

